/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Resources.GameUtil;
import javax.swing.ImageIcon;

/**
 *
 * @author Nadav
 */
public class WiningPopup extends javax.swing.JFrame {

    /**
     * Creates new form WinPopup
     */
    public WiningPopup() {
        initComponents();
        GameUtil.WinPot();
        this.setResizable(false);
        String file = "./src/img/card-symbols_bsmall.png";
                ImageIcon img = new ImageIcon(file);
                 this.setIconImage(img.getImage());
    }
    
    public void showWin()
    {
        
        WiningPopup winPopup = new WiningPopup();
        winPopup.setVisible(true);
        new java.util.Timer().schedule(
                new java.util.TimerTask() {
            @Override
            public void run() {
                winPopup.dispose();
            }
        },
                7000
        );
        

                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labWin1 = new javax.swing.JLabel();
        labWin6 = new javax.swing.JLabel();
        labWin2 = new javax.swing.JLabel();
        labWin3 = new javax.swing.JLabel();
        labWin4 = new javax.swing.JLabel();
        labWin5 = new javax.swing.JLabel();
        labWin7 = new javax.swing.JLabel();
        labWin8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labWin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win1.png"))); // NOI18N
        getContentPane().add(labWin1);
        labWin1.setBounds(0, 230, 280, 50);

        labWin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win6.png"))); // NOI18N
        getContentPane().add(labWin6);
        labWin6.setBounds(200, 0, 310, 70);

        labWin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win2.png"))); // NOI18N
        getContentPane().add(labWin2);
        labWin2.setBounds(10, 180, 290, 60);

        labWin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win3.png"))); // NOI18N
        getContentPane().add(labWin3);
        labWin3.setBounds(20, 100, 330, 60);

        labWin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win4.png"))); // NOI18N
        getContentPane().add(labWin4);
        labWin4.setBounds(20, 50, 290, 50);

        labWin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win5.png"))); // NOI18N
        getContentPane().add(labWin5);
        labWin5.setBounds(20, -10, 320, 100);

        labWin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win7.png"))); // NOI18N
        getContentPane().add(labWin7);
        labWin7.setBounds(200, 130, 300, 50);

        labWin8.setFont(new java.awt.Font("Meiryo UI", 1, 48)); // NOI18N
        labWin8.setText("YOU WIN!");
        getContentPane().add(labWin8);
        labWin8.setBounds(220, 210, 300, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/giphy.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 301);

        setSize(new java.awt.Dimension(505, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WiningPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WiningPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WiningPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WiningPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WiningPopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labWin1;
    private javax.swing.JLabel labWin2;
    private javax.swing.JLabel labWin3;
    private javax.swing.JLabel labWin4;
    private javax.swing.JLabel labWin5;
    private javax.swing.JLabel labWin6;
    private javax.swing.JLabel labWin7;
    private javax.swing.JLabel labWin8;
    // End of variables declaration//GEN-END:variables
}
